/*Crear un documento con el nombre ej88.js
Copiar y pegar el código del ejercicio ej68.js: Mostrar en consola los números pares del 0 al 1000 utilizando la estructura while


var numero = 0;

while (numero <= 1001) {
    console.log (numero);
    numero = numero + 2; 
}

//Modificar el código utilizando la estructura for en lugar de do/while*/

for (var numero = 0; numero < 1001; numero +=2) {
    console.log(numero);
}

